### ISSUE TITLE
TypeError: Cannot set property 'parent' of undefined

### ISSUE THREAD

**Issue by pspi** [lasar/dynalist-js#12]
I managed to end up in a situation where dynalist-js is no longer able to parse the Dynalist document tree. It's a fairly large document and I just recently moved a lot of nodes around. I think Dynalist itself might have corrupted its internal data - some node is a missing parent / referencing to a nonexistent parent. However, the Dynalist web app and Mac client didn't break and both are able to continue working with its data. Unfortunately, dynalist-js is no longer able to parse the document.

Would you able to if-then-else around this specific edge case in the library?

```
TypeError: Cannot set property 'parent' of undefined
    at /opt/projects/node_modules/dynalist-js/src/utilities.js:32:46
    at Array.forEach (<anonymous>)
    at Utilities.buildNodeMap (/opt/projects/node_modules/dynalist-js/src/utilities.js:26:24)
    at DocumentStore.setDocument (/opt/projects/src/service/dynalistdocumentstore.js:23:31)
    at DocumentStore.getDocument (/opt/projects/src/service/dynalistdocumentstore.js:16:12)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

Dynalist-js version 1.0.2.

**Comment by lasar** [comment]
Hi there,

I have not encountered that issue, sounds messy. I hope your data is intact otherwise.

I've made changes to the code that SHOULD help your issue. Can you test the branch issue-1 #13 to see if it works for you? If it work's I'll merge the changes and publish a new version.

**Comment by pspi** [comment]
I can confirm that fix works. Thanks so much!
